name: Bug Report
description: Let us know about problem
body:
  - type: markdown
    attributes:
      value: |
        > DON'T CREATE SECURITY ISSUE here, use [this form](https://www.yiiframework.com/security) instead.
  - type: textarea
    id: description
    attributes:
      label: Description
      description:
        Provide a detailed description of the issue. Include all relevant information to help us understand and reproduce the problem.
    validations:
      required: true
