name: Update translations

on:
  pull_request:
    paths:
      - '_translations/**'
  push:
    branches: [ "master" ]
    paths:
      - '_translations/**'
      - 'src/**'

permissions:
  contents: write
jobs:
  update-docs:
    name: Update docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          token: ${{ secrets.YIISOFT_GITHUB_TOKEN || github.token }}
          ref: ${{ github.head_ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          persist-credentials: false

      - name: Prepare po4a configuration
        run: _translations/prepare-config.sh

      - name: Use po4a
        uses: vjik/docker-run@623c9adf6ee99fc8f9fa4e3b0b6b0c25859b69ee
        with:
          image: ghcr.io/yiisoft-contrib/po4a:0.74
          volumes: ${{ github.workspace }}:/src
          workdir: /src/_translations
          command: po4a po4a.conf && po4a po4a.conf

      - name: Configure Git credentials
        env:
          GH_TOKEN: ${{ secrets.YIISOFT_GITHUB_TOKEN || github.token }}
        run: git config --global credential.helper '!f() { echo username=x-access-token; echo password=$GH_TOKEN; }; f'

      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403
        with:
          commit_message: Update translation
          file_pattern: '_translations src'
